# Generated by Django 3.2.25 on 2025-06-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingresult',
            old_name='matched_date',
            new_name='date_analyse',
        ),
        migrations.RenameField(
            model_name='matchingresult',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='matchingresult',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='matchingresult',
            name='failure_rate',
        ),
        migrations.RemoveField(
            model_name='matchingresult',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='matchingresult',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='niveau_pred',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='texte_nettoye',
            field=models.TextField(default=' '),
        ),
    ]
